<?php
include_once 'server.php';
$currentQ = $_SESSION["currentQuestion"];
$row_answers=0;
$numAnswersQuery = "SELECT * FROM answers where refQuestion = '$currentQ[questionID]'";
$result_numAnswers = mysqli_query($db, $numAnswersQuery);
$ans = mysqli_fetch_assoc($result_numAnswers);
$row_answers = mysqli_num_rows($result_numAnswers);

$asker_query = "SELECT username FROM users where userID = '$currentQ[asker]'";
$asker_result = mysqli_query($db, $asker_query);
$askerName=mysqli_fetch_assoc($asker_result);

?>




<div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-2">
        <div class="well">
            <p><?php echo($askerName['username']); ?></p>
            <img src="download.png" class="img-circle" height="55" width="55" alt="Avatar">
        </div>
    </div>
    <div class="col-sm-9">
        <div class="well">
            <div class="panel panel-default">

                <div class="panel-heading" data-questionID="<?php echo($currentQ['questionID']); ?>" >

                    <h4 id="left"> <?php echo($currentQ['title']); ?></h4>
                    <p id="left"><?php echo($currentQ['questionText']); ?></p>
					<div class="vote roundrect">
					  <div class="increment up"></div>

            <div class="increment down"></div>
            <div class="count" id= "<?php echo($currentQ['questionID']);?>"> <?php echo($currentQ['voteCount']); ?> </div>



	    </div>
            </div>
				
                <?php
                if($row_answers != 0) {
                    // print answers
                    echo("<div class = \"panel-body\">");
                    //echo($row_answers);
                    for($n = 0; $n < $row_answers; $n++){
                        if ($n>0){
                            echo("<div class=\"modal-footer\"></div>");
                        }
                        $answer_n_Query= "SELECT * FROM answers where refQuestion = '$currentQ[questionID]' ORDER BY answerID ASC LIMIT 1 OFFSET $n";
                        $answerResult = mysqli_query($db, $answer_n_Query);

                        $currentAnswer = mysqli_fetch_assoc($answerResult);
                        mysqli_free_result($answerResult);

                        print_r($currentAnswer);

                        //upvote and down vote for answer
                        $OP = $currentQ['asker'];
                        $questionID = $currentQ['questionID'];
                        $answerID = $currentAnswer['answerID'];
                        echo '<p id="left">'.$currentAnswer['voteCount'].'</p>';
                        echo '<div class="vote roundrect">';
                        echo '<div class="increment up" name = "upvote"></div>';
                        echo '<div class="increment down"></div>';

                        if (isset($_POST['upvote'])){
                            $bestQuery = "UPDATE answers SET voteCount = (voteCount+1) WHERE answerID = $answerID and refQuestion = $questionID";
                            echo("Success");
                          }

			echo '<input class="star" type="checkbox" title="bookmark page" checked><br/><br/>';



                        echo '</div>';

                        //Best answer goes here
                        $OP = $currentQ['asker'];
                        $questionID = $currentQ['questionID'];
                        $answerID = $currentAnswer['answerID'];
                        echo '<form method="post">
                        <input type="submit" name="button1"
                                value="Best Answer"/></form>';
                        if(isset($_POST['button1'])) {
                            if(isset($_SESSION['userID'])){
                                $currentUser = $_SESSION['userID'];
                            
                                if ($currentUser == $OP){
                                  $bestQuery = "UPDATE answers SET isBest = 1 WHERE answerID = $answerID and refQuestion = $questionID";
                                  echo("Success");
                                }
                                mysqli_query($db,$bestQuery);
                              }
                        }

                        //getting user name of
                        $userNameQuery = "SELECT * FROM users where userID = '$currentAnswer[answerer]'";
                        $userPoster = mysqli_query($db, $userNameQuery);
                        $UN = mysqli_fetch_assoc($userPoster);

                        
                        echo("<p id=\"left\"> Username: ". $UN['username'] . "</p>");
                        $answerText = $currentAnswer['answerText'];
                        echo("<p id=\"center\">". $answerText . "</p>");
                    }
                    echo("</div>");
                    // close the result.
                    mysqli_free_result($result_numAnswers);
                }
                ?>


                </div>
                <div class="panel-footer">
                    <div class="form-floating">
                        <form id="form" method="post">
                            <input type="hidden" name="submitAnswer" value="1" />
                            <input type="hidden" name="refQuestion" value="<?php echo($currentQ['questionID']); ?>" />
                            <textarea class="form-control" id="userAnswer" name="userAnswer" rows=2 cols="50" required placeholder="Answer question here"></textarea>
                            <input type="submit" class="btn btn-default" value="Submit Answer">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
